const { test } = require('node:test')
const assert = require('node:assert/strict')
const Database = require('better-sqlite3')
const installBoards = require('../server/boards.cjs')
const { spawn } = require('node:child_process')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const crypto = require('node:crypto')
const net = require('node:net')
const { once } = require('node:events')
const { utils } = require('ssh2')

test('board migration preserves existing records and is safe to repeat', () => {
  const db = new Database(':memory:')
  db.pragma('foreign_keys = ON')
  db.exec('CREATE TABLE nodes (id TEXT PRIMARY KEY, encrypted_key TEXT); CREATE TABLE edges (source TEXT, target TEXT);')
  db.prepare('INSERT INTO nodes VALUES (?, ?)').run('original', 'unchanged-encrypted-key')
  db.prepare('INSERT INTO nodes VALUES (?, ?)').run('service', null)
  db.prepare('INSERT INTO edges VALUES (?, ?)').run('original', 'service')
  installBoards(db)
  db.prepare('INSERT INTO boards VALUES (?, ?, ?)').run('second', 'Second board', '2026-01-01')
  db.prepare('UPDATE board_nodes SET board_id = ? WHERE node_id = ?').run('second', 'service')
  installBoards(db)
  assert.equal(db.prepare('SELECT encrypted_key FROM nodes WHERE id = ?').get('original').encrypted_key, 'unchanged-encrypted-key')
  assert.equal(db.prepare('SELECT board_id FROM board_nodes WHERE node_id = ?').get('original').board_id, 'default')
  assert.equal(db.prepare('SELECT board_id FROM board_nodes WHERE node_id = ?').get('service').board_id, 'second')
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM edges').get().n, 1)
  assert.throws(() => db.prepare('DELETE FROM boards WHERE id = ?').run('second'), /FOREIGN KEY/)
  db.prepare('DELETE FROM nodes WHERE id = ?').run('service')
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM board_nodes WHERE node_id = ?').get('service').n, 0)
  db.close()
})

test('boards isolate resources and links, persist names, and protect nonempty graphs', async () => {
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'orbit-ops-boards-'))
  const probe = net.createServer().listen(0, '127.0.0.1')
  await once(probe, 'listening')
  const port = probe.address().port
  await new Promise((resolve) => probe.close(resolve))
  const child = spawn(process.execPath, ['server/index.cjs'], { cwd: path.resolve(__dirname, '..'), env: { ...process.env, PORT: String(port), HOST: '127.0.0.1', DATA_DIR: fixture, NODE_ENV: 'production', COOKIE_SECURE: 'false', ADMIN_PASSWORD: 'isolated-board-check', SESSION_SECRET: crypto.randomBytes(32).toString('hex'), DATA_ENCRYPTION_KEY: crypto.randomBytes(32).toString('hex') }, stdio: ['ignore', 'pipe', 'pipe'] })
  let cookie = ''
  const api = async (route, method = 'GET', body) => {
    const response = await fetch(`http://127.0.0.1:${port}/api${route}`, { method, headers: { Cookie: cookie, 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) })
    if (route === '/session') cookie = response.headers.get('set-cookie')?.split(';')[0] || ''
    return { status: response.status, data: response.status === 204 ? null : await response.json() }
  }
  try {
    await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Fixture server did not start')), 10_000)
      child.stdout.on('data', (data) => { if (String(data).includes('Orbit Ops listening')) { clearTimeout(timer); resolve() } })
      child.on('error', reject)
      child.on('exit', (code) => { if (code) { clearTimeout(timer); reject(new Error('Fixture exited: ' + code)) } })
    })
    assert.equal((await api('/graph')).status, 401)
    const malformed = await fetch(`http://127.0.0.1:${port}/api/session`, { headers: { Cookie: 'orbit_session=%E0%A4%A' } })
    assert.equal(malformed.status, 200)
    assert.equal((await malformed.json()).authenticated, false)
    assert.equal((await api('/session', 'POST', { password: 'isolated-board-check' })).status, 200)
    const created = await api('/boards', 'POST', { name: 'Cloudflare / 家庭' })
    assert.equal(created.status, 201)
    const boardId = created.data.board.id
    const original = await api('/nodes', 'POST', { type: 'service', name: 'Original service' })
    const separate = await api('/nodes', 'POST', { type: 'service', name: 'Separate service', boardId })
    const sibling = await api('/nodes', 'POST', { type: 'service', name: 'Sibling service', boardId })
    assert.equal(original.status, 201)
    assert.equal(separate.status, 201)
    assert.equal((await api('/edges', 'POST', { source: original.data.node.id, target: separate.data.node.id })).status, 400)
    assert.equal((await api('/nodes', 'POST', { type: 'service', name: 'Bad link', boardId, parentId: original.data.node.id })).status, 400)
    assert.equal((await api('/nodes', 'POST', { type: 'service', name: 'Bad board', boardId: 'missing' })).status, 400)
    assert.equal((await api('/edges', 'POST', { source: separate.data.node.id, target: sibling.data.node.id })).status, 201)
    let graph = await api('/graph?boardId=' + boardId)
    assert.equal(graph.data.nodes.length, 2)
    assert.equal(graph.data.edges.length, 1)
    assert.equal((await api('/graph')).data.nodes.length, 1)
    assert.equal((await api('/boards/' + boardId, 'DELETE')).status, 409)
    assert.equal((await api('/boards/default', 'DELETE')).status, 409)
    assert.equal((await api('/boards/' + boardId, 'PATCH', { name: 'Renamed graph' })).status, 200)
    graph = await api('/graph?boardId=' + boardId)
    assert.equal(graph.data.boards.find((board) => board.id === boardId).name, 'Renamed graph')
    const serviceEdit = await api('/nodes/' + separate.data.node.id, 'PATCH', { name: 'Edited service', provider: 'Docker', endpoint: 'http://127.0.0.1:8090', notes: 'Updated from edit form' })
    assert.equal(serviceEdit.status, 200)
    assert.equal(serviceEdit.data.node.data.name, 'Edited service')
    assert.equal(serviceEdit.data.node.data.provider, 'Docker')
    assert.equal(serviceEdit.data.node.data.endpoint, 'http://127.0.0.1:8090')
    assert.equal(serviceEdit.data.node.data.notes, 'Updated from edit form')
    const fixtureKey = utils.generateKeyPairSync('ed25519')
    const createdVps = await api('/nodes', 'POST', { type: 'vps', name: 'Fixture VPS', host: '203.0.113.10', port: 22, username: 'root', privateKey: fixtureKey.private, boardId })
    assert.equal(createdVps.status, 201)
    const editedVpsId = createdVps.data.node.id
    const db = new Database(path.join(fixture, 'orbit-ops.sqlite'))
    db.prepare("UPDATE nodes SET host_fingerprint = ?, connection_status = 'connected', last_checked_at = ? WHERE id = ?").run('SHA256:fixture-old', '2026-01-01T00:00:00.000Z', editedVpsId)
    db.close()
    const vpsEdit = await api('/nodes/' + editedVpsId, 'PATCH', { name: 'Edited VPS', host: '203.0.113.11', port: 2200, username: 'admin', location: 'Tokyo', notes: 'Updated endpoint' })
    assert.equal(vpsEdit.status, 200)
    assert.equal(vpsEdit.data.node.data.name, 'Edited VPS')
    assert.equal(vpsEdit.data.node.data.host, '203.0.113.11')
    assert.equal(vpsEdit.data.node.data.port, 2200)
    assert.equal(vpsEdit.data.node.data.username, 'admin')
    assert.equal(vpsEdit.data.node.data.location, 'Tokyo')
    assert.equal(vpsEdit.data.node.data.hostFingerprint, '')
    assert.equal(vpsEdit.data.node.data.connectionStatus, 'untested')
    assert.equal(vpsEdit.data.node.data.lastCheckedAt, '')
    assert.equal(vpsEdit.data.node.data.hasPrivateKey, true)
    const invalidEdit = await api('/nodes/' + editedVpsId, 'PATCH', { port: 70000 })
    assert.equal(invalidEdit.status, 400)
    const movedVps = await api('/nodes/' + editedVpsId, 'PATCH', { x: 275, y: 340 })
    assert.equal(movedVps.status, 200)
    assert.deepEqual(movedVps.data.node.position, { x: 275, y: 340 })
    await api('/nodes/' + editedVpsId, 'DELETE')
    await api('/nodes/' + separate.data.node.id, 'DELETE')
    await api('/nodes/' + sibling.data.node.id, 'DELETE')
    assert.equal((await api('/graph?boardId=' + boardId)).data.edges.length, 0)
    assert.equal((await api('/boards/' + boardId, 'DELETE')).status, 204)
    assert.equal((await api('/graph?boardId=' + boardId)).status, 404)
    assert.equal((await api('/graph')).data.nodes[0].data.name, 'Original service')
  } finally {
    child.kill()
    if (child.exitCode === null) await once(child, 'exit')
    const resolved = path.resolve(fixture)
    if (path.dirname(resolved) === path.resolve(os.tmpdir()) && path.basename(resolved).startsWith('orbit-ops-boards-')) fs.rmSync(resolved, { recursive: true, force: true })
  }
})
